### ISSUE TITLE
Minor Issues on README

### ISSUE THREAD

**Issue by tokoharu** [wind23/whr_renju#5]
Firstly, the following page has been flagged as "Not Found," and I kindly request an update:

http://renju.net/downloads/games.php

Additionally, the phrase "After the database is ready, you can simply run" seems outdated. It appears that there is a need to add a statement for the third argument, such as "[CATEGORY]" (that means renju / gomoku).

**Comment by wind23** [comment]
README is updated.

**Comment by tokoharu** [comment]
@wind23 Thanks!
